### ISSUE TITLE
BlueCat provider cleanup error 

### ISSUE THREAD

**Issue by dittman1** [go-acme/lego#1626]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

The TXT record removed after validation.

### What did you see instead?

There is an error when performing cleanup and the TXT record remains in BlueCat.

### How do you use lego?

Binary

### Reproduction steps

I run the command:

```
./lego --server="https://acme-staging-v02.api.letsencrypt.org/directory" --dns="bluecat" --domains="myhost.mydomain" --email="me@mydomain.net" run
```

### Version of lego

```console
lego version 4.6.0 linux/amd64
```

### Logs

```
2022/04/13 09:31:29 [WARN] [bam.mydomain] acme: cleaning up failed: bluecat: request failed with HTTP status code 404 Full message: {"status":404,"reason":"Not Found","code":"ResourceNotFound","message":"The requested resource was not found"}
```

**Comment by ldez** [comment]
Hello,

I improved the Bluecat implementation, mainly because the error message was a bit unclear.

Are you able to test my PR #1627?

**Comment by dittman1** [comment]
Let me see if I can build it.

**Comment by dittman1** [comment]
I was unable to built it.  I don't normally use go so I installed the packages on RHEL 8.  Make fails because golangci-lint doesn't exist and I can't find it for RHEL 8.  I tried installing the suggested package buildah-tests but that doesn't provide it.

**Comment by dittman1** [comment]
I think I was able to build it, but the test version doesn't even get the TXT record added it:

`# ./lego-test --server="https://acme-staging-v02.api.letsencrypt.org/directory" --dns="bluecat" --domains=“myhost.mydomain” --email=“me@mydomain” run
2022/04/18 11:37:36 [INFO] [myhost.mydomain] acme: Obtaining bundled SAN certificate
2022/04/18 11:37:36 [INFO] [myhost.mydomain] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2220594883
2022/04/18 11:37:36 [INFO] [myhost.mydomain] acme: Could not find solver for: tls-alpn-01
2022/04/18 11:37:36 [INFO] [myhost.mydomain] acme: Could not find solver for: http-01
2022/04/18 11:37:36 [INFO] [myhost.mydomain] acme: use dns-01 solver
2022/04/18 11:37:36 [INFO] [myhost.mydomain] acme: Preparing to solve DNS-01
2022/04/18 11:37:36 [INFO] [myhost.mydomain] acme: Cleaning DNS-01 challenge
2022/04/18 11:37:36 [WARN] [myhost.mydomain] acme: cleaning up failed: bluecat: lookupParentZoneID: could not find zone named _acme-challenge.myhost
2022/04/18 11:37:36 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2220594883
2022/04/18 11:37:36 Could not obtain certificates:
	error: one or more domains had a problem:
[myhost.mydomain] [myhost.mydomain] acme: error presenting token: bluecat: lookupParentZoneID: could not find zone named _acme-challenge.myhost
`

**Comment by ldez** [comment]
I updated the PR, can you try again?

**Comment by dittman1** [comment]
No change, I get the same output.  One thing I noticed is when I built it originally it did a lot more work, this time a build just di "go build ..." for dist/lego.  I removed the directory and cloned along with the gh pr and tried again and it still just does this:

`[root@linuxgui lego]# make build
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: c39d319a2b25ca4434b35180b21ee236ed41233b
go build -v -trimpath -ldflags '-X "main.version=c39d319a2b25ca4434b35180b21ee236ed41233b"' -o  dist/lego ./cmd/lego/
`

**Comment by ldez** [comment]
> One thing I noticed is when I built it originally it did a lot more work, this time a build just di "go build ..." for dist/lego. I removed the directory and cloned along with the gh pr and tried again and it still just does this:

it's expected: first you have to download the dependencies (the dependencies are not store inside the project) and after the first build Go uses a cache.

---

> No change, I get the same output.

it's not possible because I removed the error message, can you give me the log?

**Comment by dittman1** [comment]
I created a new directory and did a git clone followed by "gh pr checkout 1627", then "make build"  Is it a different PR to check out?  I removed the first pull just to be sure I wasn't pulling the wrong one.  Here's what I get with the new build:

`# ./lego --server="https://acme-staging-v02.api.letsencrypt.org/directory" --dns="bluecat" --domains=“myhost.mydomain” --email=“me”@mydomain” run
2022/04/18 19:23:40 [INFO] [myhost.mydomain] acme: Obtaining bundled SAN certificate
2022/04/18 19:23:41 [INFO] [myhost.mydomain] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2223575574
2022/04/18 19:23:41 [INFO] [myhost.mydomain] acme: Could not find solver for: tls-alpn-01
2022/04/18 19:23:41 [INFO] [myhost.mydomain] acme: Could not find solver for: http-01
2022/04/18 19:23:41 [INFO] [myhost.mydomain] acme: use dns-01 solver
2022/04/18 19:23:41 [INFO] [myhost.mydomain] acme: Preparing to solve DNS-01
2022/04/18 19:23:42 [INFO] [myhost.mydomain] acme: Cleaning DNS-01 challenge
2022/04/18 19:23:43 [WARN] [myhost.mydomain] acme: cleaning up failed: bluecat: delete TXT record: status code: 200, message:  
2022/04/18 19:23:43 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2223575574
2022/04/18 19:23:43 Could not obtain certificates:
	error: one or more domains had a problem:
[myhost.mydomain] [myhost.mydomain] acme: error presenting token: bluecat: deploy: status code: 200, message: 
`
I messed up previously.  This is the new error.

**Comment by ldez** [comment]
I updated the PR, can you try again?

FYI, the Bluecat API doesn't seem to follow the Bluecat API doc.

**Comment by dittman1** [comment]
Okay, it's adding and deleting the TXT record correctly, but it doesn't look like the deploy is being done to update the servers so the record doesn't resolve.

If I enable Dynamic Deployment for the zone in BlueCat it works, but that's a new 9.4 feature and also will not likely be enabled by everyone.

**Comment by ldez** [comment]
We use the `quickDeploy` endpoint for the deployment.

https://docs.bluecatnetworks.com/r/Address-Manager-API-Guide/POST/v1/quickDeploy/9.1.0

It's the same call as before my PR.

**Comment by ldez** [comment]
I added a debug option `BLUECAT_DEBUG`, this option will display the information before calling the deployment.

Can you try to see if there are some problems with the zoneID?

**Comment by dittman1** [comment]
The zone ID is correct, as is the view ID.  It's deploying now.  There is a bit of a delay for the server to validate the request, about 30 seconds after it starts resolving at all the authoritative servers.  I'm guessing that's something outside of the bluecat code.

**Comment by ldez** [comment]
so I will merge the PR.

Can I also close this issue?

**Comment by dittman1** [comment]
I think it's good.  Thank you!
